# Generated by Django 5.0.3 on 2024-06-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odisea", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"verbose_name": "Author", "verbose_name_plural": "Authors"},
        ),
        migrations.AlterModelOptions(
            name="reader",
            options={"verbose_name": "Reader", "verbose_name_plural": "Readers"},
        ),
        migrations.AddField(
            model_name="author",
            name="bio",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
