# Generated by Django 5.0.3 on 2024-06-12 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("odisea", "0002_alter_author_options_alter_reader_options_author_bio"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={
                "permissions": [
                    ("new", "Can view the new page and create blogs there.")
                ],
                "verbose_name": "Author",
                "verbose_name_plural": "Authors",
            },
        ),
    ]
