# Generated by Django 5.0.3 on 2024-06-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("odisea", "0003_alter_author_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.CharField(
                choices=[
                    ("Personal", "Personal"),
                    ("Sports", "Sports"),
                    ("Books", "Books"),
                    ("Cinema", "Cinema"),
                ],
                default=None,
                max_length=150,
            ),
        ),
    ]
