# Generated by Django 5.1 on 2024-08-16 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odisea", "0006_article_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
