# Generated by Django 5.1 on 2024-08-17 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odisea", "0007_alter_article_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.CharField(
                choices=[
                    ("Personal", "Personal"),
                    ("Sports", "Sports"),
                    ("Books", "Books"),
                    ("Cinema", "Cinema"),
                ],
                default="Personal",
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
